# Generated by Django 2.2 on 2020-06-11 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_auto_20200611_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 32, 47, 483640, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
